---

# Default setting

# Image type to use in the analysis ("amp" or "eimage")
imageType: amp

# 1 pixel = 0.2 arcsec
pixelToArcsec: 0.2

# Bright star catalog (BSC) database type ("localDb" or "file")
# localDb: Use the local database (not support yet)
# file: Use the sky file
# image: Use the image to get donuts
# refCat: Use the image to fit a DM RefCat
bscDbType: refCat

# Default BSC database path relative to the root of module
defaultBscPath: tests/testData/bsc.db3

# Default sky file path relative to the root of module
# This is for the test only
defaultSkyFilePath: tests/testData/phosimOutput/realComCam/skyComCamInfo.txt

# Camera MJD
cameraMJD: 59580.0

# Star (donut) radious in pixel
# Donut radius is 63 pixel if the defocal distance is 1.5 mm
starRadiusInPixel: 63

# Spacing coefficient
spacingCoef: 2.5

# Max number of neighboring star (0 or 1)
# At this moment, we only plan to support the maximum number of 1
maxNumOfNbrStar: 1

# Distance to be vignette
distVignette: 1.75

# Algorithm to solve the Poisson's equation in the transport of intensity
# equation (TIE). It can be "fft" or "exp".
poissonSolver: exp

# Optical model. It can be "paraxial", "onAxis", or "offAxis"
opticalModel: offAxis

# Defocal distance in mm (default is 1.5 mm)
defocalDistInMm: 1.5

# Donut image size in pixel (default value at 1.5 mm)
donutImgSizeInPixel: 160

# Centroid find algorithm. It can be "randomWalk" or "otsu"
centroidFindAlgo: randomWalk

# Camera mapper for the data butler to use
camMapper: phosim

# Instrument signature removal (ISR) rerun name
rerunName: run1

# Offset to the dimension of camera. If the detector dimension is 10 (assume
# 1-D), the star's position between -offset and 10+offset will be seem to be on
# the detector.
camDimOffset: 0

# Do the deblending or not (we do not have the functionable deblending
# algorithm yet)
doDeblending: True

# Deblending donut algorithm to use. ("adapt" or "convolveTemplate")
deblendDonutAlgo: convolveTemplate

# Which type of template to use with new centroid algorithms
# 'phosim' or 'model'
centroidTemplateType: model

# Set to use isolated donut in image for deblending if possible
# Separate from command above because won't have an isolated template
# for initial centroiding
# Can be 'phosim', 'model', or 'isolatedDonutFromImage'
deblendTemplateType: isolatedDonutFromImage

# If using the image to construct donut database
# This is the minimum distance two donut centers need to be to
# be tagged as unblended (in pixels)
minUnblendedDistance: 160

# Limit the number of stars used when running with `isolatedDonutFromImage`
# Can be None or an integer
maxSensorStars: 5

# Location of reference catalog for WCS generation
refCatDir: /astro/users/ajc26/epycuser/LSST-Commissioning/aoc/gaia_refcat

# Number of processor for the parallel calculation (should be >=1)
# This is just a placeholder at this moment
# This will begin to work when the super task is implemented
numOfProc: 1
